config/routes.rb
Rails.application.routes.draw do
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]

  get 'home/top'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'home#top'
  get "home/about" => "home#about", as: "about"
  
  resources :users, only: [:show, :edit, :index, :update]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

    
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?
before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end
  
  def show
    @book = Book.find(params[:id])
    @book2 = Book.new
    @user = @book.user
  end
  def edit
    is_matching_book
      @book = Book.find(params[:id])
  end
  
  def update
    is_matching_book
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully updated.'
      redirect_to book_path(@book.id) 
    else
      render :edit
    end 
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to "/books"
  end
    # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
    def is_matching_book
      user = Book.find(params[:id]).user
      unless user.id == current_user.id
        redirect_to "/books"
      end
    end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    super
    flash[:notice] = "Signed in successfully.
" if signed_in?
  end

  def new
    super
  end

  def destroy
    super
    flash[:notice] = "Signed out successfully." unless signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book = Book.new
    @users = User.all
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    is_matching_login_user

    @user = User.find(params[:id])
  end

  def update
    is_matching_login_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
     render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :introduction,:profile_image) # 必要な属性を指定します
  end
  
    def is_matching_login_user
      user = User.find(params[:id])
      unless user.id == current_user.id
        redirect_to user_path(current_user)
      end
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
    
      <div class="order-md-last">
        <h1>New book</h1>
        <%= form_with model: @book do |f| %>
          <h4>Title</h4>
          <%= f.text_field :title %>
          <h4>Opinion</h4>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>
      </div>

app/views/books/edit.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= flash[:notice] %>

  <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this obj from being saved:<br>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>


</div>

    <div class="d-flex flex-column align-items-center justify-content-center ">
      <div>
          <h1>Editing Book</h1>
          <%= form_with model: @book do |f| %>
            <h4>Title</h4><br>
            <%= f.text_field :title %><br>
            <h4>Opinion</h4><br>
            <%= f.text_area :body %><br>
            <%= f.submit 'Update Book', class:"btn btn-success" %>
          <% end %>
        <%= link_to "Show", book_path(@book.id)%>
        |
        <%= link_to "Back", "/books" %>
      </div>
    </div>
  </div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
    <%= flash[:notice] %>

  <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this obj from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>


</div>

<div class="container">
  <div class="row">
    <div class="col-md-3">
            <div>
        <h2>User info</h2>
        <%= image_tag current_user.get_profile_image(100,100) %>
        <table>
          <tbody>
            <tr>
              <th>name</th>
              <td><%= current_user.name %></td>
            </tr>
            <tr>
              <th>introduction</th>
              <td><%= current_user.introduction %></td>
            </tr>
          </tbody>
        </table>
        <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary" do %>
          　　　　　　<i class="fas fa-user-cog"></i>　
          　　　　　　<% end %>
      </div>

      <%= render 'list' %>

    </div>







    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table>
        <thead>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
        </thead>
        <tbody>
        <% @books.each do |book1| %>
          <tr>
            <td><%= link_to user_path(book1.user_id), class: "text-decoration-none" do %>
            <%= image_tag book1.user.get_profile_image(100,100) %>
            <% end %>
            </td>
        <td><%= link_to book1.title, book_path(book1.id) %></td>
        <td><%= book1.body %></td>
          </tr>
        <% end %>
        </tbody>

      </table>
    </div>
  </div>  <!-- この行を追加 -->
</div>

app/views/books/show.html.erb
    <%= flash[:notice] %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
            <div>
        <h2>User info</h2>
        <%= image_tag @book.user.get_profile_image(100,100) %>
        <table>
          <tbody>
            <tr>
              <th>name</th>
              <td><%= @book.user.name %></td>
            </tr>
            <tr>
              <th>introduction</th>
              <td><%= @book.user.introduction %></td>
            </tr>
          </tbody>
        </table>

            <%= link_to edit_user_path(@book.user), class: "btn btn-outline-secondary" do %>
      　　　　　　<i class="fas fa-user-cog"></i>　　　　　
      　　　　　　<% end %>
            </div>
      
    
      <div class="order-md-last">
        <h1>New book</h1>
        <%= form_with model: @book2 do |f| %>
          <h4>Title</h4>
          <%= f.text_field :title %>
          <h4>Opinion</h4>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>
      </div>

    </div>
    
    
    
    
    
    

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table>
        <tbody>
          <tr>
            <td>
            <%= link_to user_path(@book.user_id), class: "text-decoration-none" do %>
              <%= image_tag @book.user.get_profile_image(100,100) %>
              <br><%= @user.name %>
            <% end %>
              </td>
        <td><%= link_to @book.title, book_path(@book.id) %></td>
        <td><%= @book.body %></td>
        <% if current_user == @user %>
          <td><%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-sm btn-success" %></td>
          <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn btn-sm btn-danger" %></td>
        <% end %>
          </tr>
        </tbody>
      
      </table>
    </div>
  </div>  <!-- この行を追加 -->
</div> 

app/views/home/about.html.erb
<div class="d-flex flex-column align-items-center justify-content-center">

  <h1>welcome to <i class="fas fa-book"></i>Bookers !!</h1>

</div>

app/views/home/top.html.erb
<div class="d-flex flex-column align-items-center justify-content-center">
  
      <%= flash[:notice] %>
      
  <h1>welcome to <i class="fas fa-book"></i>Bookers !!</h1>
  
  <p>In <i class="fas fa-book"></i><strong>Bookers,</strong></p>
  <p>you can share and exchange your opinions , inpressions , and emotions</p>
  <p>about various books!</p>
  <div >
    <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
    <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
  </div>
</div>

app/views/homes/top.html.erb
<div class="d-flex flex-column align-items-center justify-content-center">
  <h1>welcome to <i class="fas fa-book"></i>Bookers !!</h1>
  
  <p>In <i class="fas fa-book"></i><strong>Bookers,</strong></p>
  <p>you can share and exchange your opinions , inpressions , and emotions</p>
  <p>about various books!</p>
  <div >
    <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
    <%= link_to "Sign in", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <li>
        <%= link_to user_path(current_user), class:'nav-link text-light' do %>
        <i class="fas fa-home"></i>Home
        <% end %>
      </li>
      <li>
        <%= link_to users_path, class:'nav-link text-light' do %>
        <i class="fas fa-users"></i>Users
        <% end %>
      </li>
      <li>
        <%= link_to books_path, class:'nav-link text-light' do %>
        <i class="fas fa-book-open"></i>Books
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete, class:'nav-link text-light' do %>
        <i class="fas fa-sign-out-alt"></i>Log out
        <% end %>
      </li>
    <% else %>
      <li>
        <%= link_to "/", class:'nav-link text-light' do %>
        <i class="fas fa-home"></i>Home
        <% end %>
      </li>
      <li>
        <%= link_to about_path, class:'nav-link text-light' do %>
        <i class="fas fa-link"></i>About
        <% end %>
      </li>
      <li>
        <%= link_to new_user_registration_path, class:'nav-link text-light' do %>
        <i class="fas fa-user-plus"></i>Sign up
        <% end %>
      </li>
      <li>
        <%= link_to new_user_session_path, class:'nav-link text-light' do %>
        <i class="fas fa-sign-in-alt"></i>Log in
        <% end %>
      </li>
          <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
   <main class="d-flex flex-column align-items-center justify-content-center mt-3">
    <%= yield %>
   </main>
  </body>
  <footer class="d-flex flex-column align-items-center justify-content-center mt-3">
    CopyRight Infratop.inc
  </footer>
</html>

app/views/users/edit.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= flash[:notice] %>

  <% if @user.errors.any? %>
    <%= @user.errors.count %>error prohibited this obj from being saved:<br>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  </div>
</div>

      <div class="d-flex flex-column align-items-center justify-content-center ">
        <div>
        <h1>User info</h1>
        <%= form_with model: @user do |f| %>
          <label>Name</label><br>
          <%= f.text_field :name %><br>
          <label>Image</label><br>
          <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  <br>

          <label>Introduction</label><br>
          <%= f.text_area :introduction %><br>
          <%= f.submit 'Update User', class:"btn btn-secondary" %>
        <% end %>
        </div>
      </div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
            <div>
        <h2>User info</h2>
        <%= image_tag current_user.get_profile_image(100,100) %>
        <table>
          <tbody>
            <tr>
              <th>name</th>
              <td><%= current_user.name %></td>
            </tr>
            <tr>
              <th>introduction</th>
              <td><%= current_user.introduction %></td>
            </tr>
          </tbody>
        </table>
        <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary" do %>
          　　　　　　<i class="fas fa-user-cog"></i>　　　　　　
        <% end %>  
      </div>
      
      <%= render 'books/list' %>

    </div>
    
    
    
    
    
    

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table>
        <thead>
          <tr>
            <th>images</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user1| %>
          <tr>
            <td><%= image_tag user1.get_profile_image(100,100) %></td>
            <td><%= user1.name %></td>
            <td><%= link_to "Show", user_path(user1.id) %></td>
        <% end %>
          </tr>
        </tbody>
      
      </table>
    </div>
  </div>  <!-- この行を追加 -->
</div> 

app/views/users/show.html.erb
    <%= flash[:notice] %>


<div class="container">
  <div class="row">
    <div class="col-md-3">
            <div>
        <h2>User info</h2>
        <%= image_tag @user.get_profile_image(100,100) %>
        <table>
          <tbody>
            <tr>
              <th>name</th>
              <td><%= @user.name %></td>
            </tr>
            <tr>
              <th>introduction</th>
              <td><%= @user.introduction %></td>
            </tr>
          </tbody>
        </table>
            <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary" do %>
          　　　　　　<i class="fas fa-user-cog"></i>　　　　　　
          　　　　　　<% end %>

      </div>
      
      <%= render 'books/list' %>

    </div>
    
    
    
    
    
    

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book1| %>
          <tr>
            <td><%= link_to user_path(book1.user_id), class: "text-decoration-none" do %>
            <%= image_tag book1.user.get_profile_image(100,100) %>
            <% end %>
            </td>
            
            
            <td><%= link_to book1.title, book_path(book1.id) %></td>
            <td><%= book1.body %></td>
        <% end %>
          </tr>
        </tbody>
      
      </table>
    </div>
  </div>